### ISSUE TITLE
get matched points

### ISSUE THREAD

**Issue by xuzhi0413** [cosbidev/PyTrack#8]
If points include matched points and unmatched points. How can I get matched points？
Thank you very much.

**Comment by mtortora-ai** [comment]
I'm sorry but I don't understand the question, can you describe your doubt better? even giving a minimal example of your problem.

**Comment by QiuziChen** [comment]
I think the original question is how to extract matched results from the output of PyTrack. All results are stored in the output `results` of function `candidate.elab_candidate_results()` as a dict. And the chosen candidates are linked to the True value in list `candidate_type`.
